exports.identities = [ // TODO: revert id to int once graph is patched.
  { "id" : "0", "name" : "Human" },
  { "id" : "1", "name" : "Animal" },

  { "id" : "2", "name" : "Religion", "pivot" : true },
  { "id" : "3", "name" : "Ethnicity", "pivot" : true },
  { "id" : "4", "name" : "Profession", "pivot" : true },

  { "id" : "5", "name" : "Gender", "pivot" : true },
  { "id" : "6", "name" : "Parent", "pivot" : true },
  { "id" : "7", "name" : "Sibling", "pivot" : true },
  { "id" : "8", "name" : "Child", "pivot" : true },
  { "id" : "9", "name" : "Partner", "pivot" : true },

  // { "id" : "10", "name" : "Liberal" },
  // { "id" : "11", "name" : "Conservative" },

  // { "id" : "12", "name" : "Patriot" },
  // { "id" : "13", "name" : "Radical" },

  { "id" : "14", "name" : "Friend" },
  { "id" : "15", "name" : "Colleague" },

  { "id" : "16", "name" : "Partisan", "pivot" : true },
  { "id" : "17", "name" : "National", "pivot" : true },
]

exports.pivots = {
  "2": function(user) {
    return user.religion
  },
  "3": function(user) {
    return user.ethnicity
  },
  "4": function(user) {
    return user.job
  },
  "5": function(user) {
    return user.gender
  },
  "6": function(user) {
    if (user.children == "No Kids") return ""
    else if (user.gender === "Male") return "Father"
    else if (user.gender === "Female") return "Mother"
    else return "Parent"
  },
  "7": function(user) {
    if (user.siblings == "No Siblings") return ""
    else if (user.gender === "Male") return "Brother"
    else if (user.gender === "Female") return "Sister"
    else return "Sibling"
  },
  "8": function(user) {
    if (user.gender === "Male") return "Son"
    else if (user.gender === "Female") return "Daughter"
    else return "Child"
  },
  "9": function(user) {
    if (user.relationship === "Married" ) {
      if (user.gender === "Male") return "Husband"
      else if (user.gender === "Female") return "Wife"
      else return "Partner"
    } else if (user.relationship === "In a Relationship") {
      if (user.gender === "Male") return "Boyfriend"
      else if (user.gender === "Female") return "Girlfriend"
      else return "Partner"
    } else return ""
  },
  "16": function(user) {
    return user.party
  },
  "17": function(user) {
    return demonyms[user.cc] ? demonyms[user.cc] : ""
  }
}

const demonyms = {
  "NA": "Namibian",
  "AD": "Andorran",
  "AE": "Emirati",
  "AF": "Afghan",
  "AG": "Antiguan, Barbudan",
  "AI": "Anguillian",
  "AL": "Albanian",
  "AM": "Armenian",
  "AO": "Angolan",
  "AQ": "Antarctican",
  "AR": "Argentine",
  "AS": "American Samoan",
  "AT": "Austrian",
  "AU": "Australian",
  "AW": "Aruban",
  "AX": "\xc3\x85landish",
  "AZ": "Azerbaijani",
  "BA": "Bosnian, Herzegovinian",
  "BB": "Barbadian",
  "BD": "Bangladeshi",
  "BE": "Belgian",
  "BF": "Burkinabe",
  "BG": "Bulgarian",
  "BH": "Bahraini",
  "BI": "Burundian",
  "BJ": "Beninese",
  "BL": "Saint Barth\xc3\xa9lemy Islander",
  "BM": "Bermudian",
  "BN": "Bruneian",
  "BO": "Bolivian",
  "BQ": "Dutch",
  "BR": "Brazilian",
  "BS": "Bahamian",
  "BT": "Bhutanese",
  "BV": "Cape Verdian",
  "BW": "Motswana",
  "BY": "Belarusian",
  "BZ": "Belizean",
  "CA": "Canadian",
  "CC": "Cocos Islander",
  "CD": "Congolese",
  "CF": "Central African",
  "CG": "Congolese",
  "CH": "Swiss",
  "CI": "Ivorian",
  "CK": "Cook Islander",
  "CL": "Chilean",
  "CM": "Cameroonian",
  "CN": "Chinese",
  "CO": "Colombian",
  "CR": "Costa Rican",
  "CU": "Cuban",
  "CV": "Cape Verdian",
  "CW": "Dutch",
  "CX": "Christmas Islander",
  "CY": "Cypriot",
  "CZ": "Czech",
  "DE": "German",
  "DJ": "Djibouti",
  "DK": "Danish",
  "DM": "Dominican",
  "DO": "Dominican",
  "DZ": "Algerian",
  "EC": "Ecuadorean",
  "EE": "Estonian",
  "EG": "Egyptian",
  "EH": "Sahrawi",
  "ER": "Eritrean",
  "ES": "Spanish",
  "ET": "Ethiopian",
  "FI": "Finnish",
  "FJ": "Fijian",
  "FK": "Falkland Islander",
  "FM": "Micronesian",
  "FO": "Faroese",
  "FR": "French",
  "GA": "Gabonese",
  "GB": "British",
  "GD": "Grenadian",
  "GE": "Georgian",
  "GF": "Guianan",
  "GG": "Channel Islander",
  "GH": "Ghanaian",
  "GI": "Gibraltar",
  "GL": "Greenlandic",
  "GM": "Gambian",
  "GN": "Guinean",
  "GP": "Guadeloupian",
  "GQ": "Equatorial Guinean",
  "GR": "Greek",
  "GS": "South Georgian South Sandwich Islander",
  "GT": "Guatemalan",
  "GU": "Guamanian",
  "GW": "Guinea-Bissauan",
  "GY": "Guyanese",
  "HK": "Hong Konger",
  "HM": "Heard and McDonald Islander",
  "HN": "Honduran",
  "HR": "Croatian",
  "HT": "Haitian",
  "HU": "Hungarian",
  "ID": "Indonesian",
  "IE": "Irish",
  "IL": "Israeli",
  "IM": "Manx",
  "IN": "Indian",
  "IO": "Indian",
  "IQ": "Iraqi",
  "IR": "Iranian",
  "IS": "Icelander",
  "IT": "Italian",
  "JE": "Channel Islander",
  "JM": "Jamaican",
  "JO": "Jordanian",
  "JP": "Japanese",
  "KE": "Kenyan",
  "KG": "Kirghiz",
  "KH": "Cambodian",
  "KI": "I-Kiribati",
  "KM": "Comoran",
  "KN": "Kittitian or Nevisian",
  "KP": "North Korean",
  "KR": "South Korean",
  "KW": "Kuwaiti",
  "KY": "Caymanian",
  "KZ": "Kazakhstani",
  "LA": "Laotian",
  "LB": "Lebanese",
  "LC": "Saint Lucian",
  "LI": "Liechtensteiner",
  "LK": "Sri Lankan",
  "LR": "Liberian",
  "LS": "Mosotho",
  "LT": "Lithuanian",
  "LU": "Luxembourger",
  "LV": "Latvian",
  "LY": "Libyan",
  "MA": "Moroccan",
  "MC": "Monegasque",
  "MD": "Moldovan",
  "ME": "Montenegrin",
  "MF": "Saint Martin Islander",
  "MG": "Malagasy",
  "MH": "Marshallese",
  "MK": "Macedonian",
  "ML": "Malian",
  "MM": "Bamar",
  "MN": "Mongolian",
  "MO": "Macanese",
  "MP": "American",
  "MQ": "French",
  "MR": "Mauritanian",
  "MS": "Montserratian",
  "MT": "Maltese",
  "MU": "Mauritian",
  "MV": "Maldivan",
  "MW": "Malawian",
  "MX": "Mexican",
  "MY": "Malaysian",
  "MZ": "Mozambican",
  "NC": "New Caledonian",
  "NE": "Nigerien",
  "NF": "Norfolk Islander",
  "NG": "Nigerian",
  "NI": "Nicaraguan",
  "NL": "Dutch",
  "NO": "Norwegian",
  "NP": "Nepalese",
  "NR": "Nauruan",
  "NU": "Niuean",
  "NZ": "New Zealander",
  "OM": "Omani",
  "PA": "Panamanian",
  "PE": "Peruvian",
  "PF": "French Polynesian",
  "PG": "Papua New Guinean",
  "PH": "Filipino",
  "PK": "Pakistani",
  "PL": "Polish",
  "PM": "French",
  "PN": "Pitcairn Islander",
  "PR": "Puerto Rican",
  "PS": "Palestinian",
  "PT": "Portuguese",
  "PW": "Palauan",
  "PY": "Paraguayan",
  "QA": "Qatari",
  "RE": "French",
  "RO": "Romanian",
  "RS": "Serbian",
  "RU": "Russian",
  "RW": "Rwandan",
  "SA": "Saudi Arabian",
  "SB": "Solomon Islander",
  "SC": "Seychellois",
  "SD": "Sudanese",
  "SE": "Swedish",
  "SG": "Singaporean",
  "SH": "Saint Helenian",
  "SI": "Slovene",
  "SJ": "Norwegian",
  "SK": "Slovak",
  "SL": "Sierra Leonean",
  "SM": "Sammarinese",
  "SN": "Senegalese",
  "SO": "Somali",
  "SR": "Surinamer",
  "SS": "South Sudanese",
  "ST": "Sao Tomean",
  "SV": "Salvadoran",
  "SX": "St. Maartener",
  "SY": "Syrian",
  "SZ": "Swazi",
  "TC": "Turks and Caicos Islander",
  "TD": "Chadian",
  "TF": "French",
  "TG": "Togolese",
  "TH": "Thai",
  "TJ": "Tadzhik",
  "TK": "Tokelauan",
  "TL": "East Timorese",
  "TM": "Turkmen",
  "TN": "Tunisian",
  "TO": "Tongan",
  "TR": "Turkish",
  "TT": "Trinidadian",
  "TV": "Tuvaluan",
  "TW": "Taiwanese",
  "TZ": "Tanzanian",
  "UA": "Ukrainian",
  "UG": "Ugandan",
  "UM": "American",
  "US": "American",
  "UY": "Uruguayan",
  "UZ": "Uzbekistani",
  "VA": "Vatican",
  "VC": "Saint Vincentian",
  "VE": "Venezuelan",
  "VG": "Virgin Islander",
  "VI": "Virgin Islander",
  "VN": "Vietnamese",
  "VU": "Ni-Vanuatu",
  "WF": "Wallis and Futuna Islander",
  "WS": "Samoan",
  "XK": "Kosovar",
  "YE": "Yemeni",
  "YT": "Mahoran",
  "ZA": "South African",
  "ZM": "Zambian",
  "ZW": "Zimbabwean"
}